Writable:
  LogLevel: INFO
  InsecureSecrets:
    CoAP:
      SecretName: "psk"
      SecretData:
        # Key is up to 16 arbitrary bytes; must be base64 encoded here
        PskKey: ""

Service:
  Host: localhost
  Port: 59988
  StartupMsg: "CoAP device service started"

Device:
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"

Driver:
  # Supports IPv4 or IPv6 if provided by network infrastructure. Use "0.0.0.0"
  # for any IPv4 interface, or "::" for any IPv6 interface.
  CoapBindAddr: 0.0.0.0
  # Choose "PSK" or "NoSec"
  SecurityMode: NoSec

MessageBus:
  Optional:
    ClientId: device-coap
